---
- name: Prepare nodes
  hosts: all
  become: yes
  vars:
    awx_cname: awx.proxy.lab
  tasks:
    - name: Set a hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Ensure manage_etc_hosts is disabled
      ansible.builtin.lineinfile:
        path: /etc/cloud/cloud.cfg
        regexp: '^manage_etc_hosts:'
        line: 'manage_etc_hosts: False'
        state: present

    - name: Add hosts entries using template
      ansible.builtin.template:
        src: hosts.j2
        dest: /etc/hosts
      become: yes

    - name: Install Python 3
      ansible.builtin.yum:
        name: python3
        state: present
...
